### ISSUE TITLE
「タグ」「スパン」は日本語にする必要があるか？

### ISSUE THREAD

**Issue by tamuhey** [hiroshi-matsuda-rit/spacy-course#14]
そのまま英語でいいのでは？　（https://github.com/hiroshi-matsuda-rit/spacy-course/issues/4#issuecomment-691529833）

**Comment by hiroshi-matsuda-rit** [comment]
自然言語処理で一般的に使われる語義としてはタグ/スパン/文書を、
spaCyのオブジェクトを指す場合はTag/Span/Docを使用するのが分かりやすいでしょうか。

**Comment by tamuhey** [comment]
@hiroshi-matsuda-rit そうですね。そうしましょう
